import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.campaigns': 'Campaigns',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title': 'Support People in Need',
    'hero.subtitle': 'Your small contribution can bring a big change in someone\'s life.',
    'hero.cta': 'Donate Now',
    'hero.trusted': 'Trusted by 50k+ Donors',
    'hero.learn': 'Learn More',
    'categories.title': 'Browse Categories',
    'cat.medical': 'Medical',
    'cat.education': 'Education',
    'cat.mosque': 'Mosque',
    'cat.disaster': 'Disaster Relief',
    'cat.poor': 'Poor Support',
    'featured.title': 'Featured Campaigns',
    'featured.subtitle': 'Urgent causes that need your immediate attention.',
    'featured.viewall': 'View All',
    'how.title': 'How It Works',
    'how.subtitle': 'Helping others is now easier than ever.',
    'how.step1': 'Choose Campaign',
    'how.step1.desc': 'Find a cause that resonates with you.',
    'how.step2': 'Donate Securely',
    'how.step2.desc': 'Use our secure payment methods.',
    'how.step3': 'Help Someone',
    'how.step3.desc': 'See the impact of your donation.',
    'campaign.raised': 'Raised',
    'campaign.target': 'Target',
    'campaign.donors': 'Donors',
    'campaign.donate': 'Donate',
    'footer.about': 'About Us',
    'footer.about.desc': 'Amar Shadhon is a trusted public donation platform in Bangladesh, dedicated to connecting generous donors with those in urgent need.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.newsletter.title': 'Stay Updated',
    'footer.newsletter.desc': 'Subscribe to our newsletter for latest updates.',
    'footer.newsletter.placeholder': 'Email address',
    'footer.newsletter.button': 'Join',
    'donate.modal.title': 'Make a Donation',
    'donate.amount': 'Amount (৳)',
    'donate.amount.other': 'Other amount',
    'donate.method': 'Payment Method',
    'donate.name': 'Your Name (Optional)',
    'donate.name.placeholder': 'Full Name',
    'donate.phone': 'Phone Number',
    'donate.phone.placeholder': '01XXXXXXXXX',
    'donate.anonymous': 'Donate Anonymously',
    'donate.message': 'Message (Optional)',
    'donate.message.placeholder': 'Write a message of support...',
    'donate.confirm': 'Confirm Donation',
    'donate.success': 'Donation Successful!',
    'donate.success.desc': 'Thank you for your generous contribution of ৳',
    'donate.txid': 'Transaction ID',
    'donate.txid.placeholder': 'Enter TxID from SMS',
    'donate.txid.label': 'Transaction ID / Reference',
    'donate.date': 'Date',
    'donate.receipt': 'Receipt',
    'donate.share': 'Share',
    'donate.close': 'Close Window',
    'donate.how': 'How to Donate',
    'donate.how.desc': 'Please use the "Send Money" option from your {method} app to our personal number:',
    'donate.how.copy': 'Copy',
    'donate.how.note': '* After sending money, please provide your phone number and transaction details below.',
    'search.placeholder': 'Search campaigns...',
    'sort.urgent': 'Most Urgent',
    'sort.funded': 'Most Funded',
    'sort.latest': 'Latest',
    'trust.badge': '100% Secure & Verified Platform',
    'trust.title': 'Your Trust is Our Greatest Asset',
    'trust.desc': 'We manually verify every single campaign through our field agents to ensure your hard-earned money reaches the right hands. No hidden fees, no complicated processes.',
    'stat.raised': 'Total Raised',
    'stat.verified': 'Verified Campaigns',
    'stat.donors': 'Active Donors',
    'stat.success': 'Success Rate',
    'campaigns.subtitle': 'Discover and support causes that matter to you.',
    'campaigns.notfound': 'No campaigns found',
    'campaigns.notfound.desc': 'Try adjusting your search or filters.',
    'campaigns.all': 'All',
    'details.notfound': 'Campaign not found',
    'details.back': 'Back to Campaigns',
    'details.back.short': 'Back',
    'details.verified': 'Verified',
    'details.share': 'Share this campaign',
    'details.guarantee.title': 'Secure Donation Guarantee',
    'details.guarantee.desc': 'Your donation is protected by our secure payment systems. We ensure 100% transparency in fund distribution.',
    'details.faq.title': 'Frequently Asked Questions',
    'details.faq.q1': 'How will my money be used?',
    'details.faq.a1': '100% of your donation (minus payment gateway fees) goes directly to the campaign beneficiary.',
    'details.faq.q2': 'Is my donation tax-deductible?',
    'details.faq.a2': 'Yes, we provide official receipts that can be used for tax purposes in Bangladesh.',
    'details.faq.q3': 'Can I donate anonymously?',
    'details.faq.a3': 'Absolutely. You can choose to hide your name and message from the public donor list.',
    'details.raised.of': 'Raised of',
    'details.donors': 'Donors',
    'details.left': 'Days Left',
    'details.safe': 'Guaranteed Safe Checkout',
    'details.organizer': 'Organizer',
    'details.organizer.name': 'Amar Shadhon Team',
    'details.report': 'Report this campaign',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.campaigns': 'ক্যাম্পেইন',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.contact': 'যোগাযোগ',
    'hero.title': 'অসহায় মানুষের পাশে দাঁড়ান',
    'hero.subtitle': 'আপনার সামান্য অবদান কারো জীবনে বড় পরিবর্তন আনতে পারে।',
    'hero.cta': 'এখনই দান করুন',
    'hero.trusted': '৫০ হাজার+ দাতার আস্থা',
    'hero.learn': 'আরও জানুন',
    'categories.title': 'ক্যাটাগরি দেখুন',
    'cat.medical': 'চিকিৎসা',
    'cat.education': 'শিক্ষা',
    'cat.mosque': 'মসজিদ',
    'cat.disaster': 'দুর্যোগ ত্রাণ',
    'cat.poor': 'দরিদ্র সহায়তা',
    'featured.title': 'বিশেষ ক্যাম্পেইন',
    'featured.subtitle': 'জরুরি কারণ যা আপনার তাৎক্ষণিক মনোযোগ প্রয়োজন।',
    'featured.viewall': 'সব দেখুন',
    'how.title': 'কিভাবে কাজ করে',
    'how.subtitle': 'অন্যকে সাহায্য করা এখন আগের চেয়ে সহজ।',
    'how.step1': 'ক্যাম্পেইন বেছে নিন',
    'how.step1.desc': 'আপনার পছন্দের একটি কারণ খুঁজে নিন।',
    'how.step2': 'নিরাপদে দান করুন',
    'how.step2.desc': 'আমাদের নিরাপদ পেমেন্ট পদ্ধতি ব্যবহার করুন।',
    'how.step3': 'কাউকে সাহায্য করুন',
    'how.step3.desc': 'আপনার দানের প্রভাব দেখুন।',
    'campaign.raised': 'সংগৃহীত',
    'campaign.target': 'লক্ষ্য',
    'campaign.donors': 'দাতা',
    'campaign.donate': 'দান করুন',
    'footer.about': 'আমাদের সম্পর্কে',
    'footer.about.desc': 'আমার সাধন বাংলাদেশের একটি বিশ্বস্ত পাবলিক ডোনেশন প্ল্যাটফর্ম, যা উদার দাতাদের জরুরি প্রয়োজনে থাকা মানুষের সাথে সংযুক্ত করতে নিবেদিত।',
    'footer.links': 'দ্রুত লিঙ্ক',
    'footer.contact': 'যোগাযোগ করুন',
    'footer.rights': 'সর্বস্বত্ব সংরক্ষিত।',
    'footer.privacy': 'গোপনীয়তা নীতি',
    'footer.terms': 'শর্তাবলী',
    'footer.newsletter.title': 'আপডেট থাকুন',
    'footer.newsletter.desc': 'সর্বশেষ আপডেটের জন্য আমাদের নিউজলেটারে সাবস্ক্রাইব করুন।',
    'footer.newsletter.placeholder': 'ইমেইল ঠিকানা',
    'footer.newsletter.button': 'যোগ দিন',
    'donate.modal.title': 'দান করুন',
    'donate.amount': 'পরিমাণ (৳)',
    'donate.amount.other': 'অন্যান্য পরিমাণ',
    'donate.method': 'পেমেন্ট পদ্ধতি',
    'donate.name': 'আপনার নাম (ঐচ্ছিক)',
    'donate.name.placeholder': 'পুরো নাম',
    'donate.phone': 'ফোন নম্বর',
    'donate.phone.placeholder': '০১৮৮৯৪১১৬০২',
    'donate.anonymous': 'গোপনে দান করুন',
    'donate.message': 'বার্তা (ঐচ্ছিক)',
    'donate.message.placeholder': 'সমর্থনের একটি বার্তা লিখুন...',
    'donate.confirm': 'নিশ্চিত করুন',
    'donate.success': 'দান সফল হয়েছে!',
    'donate.success.desc': 'আপনার ৳{amount} উদার অবদানের জন্য ধন্যবাদ।',
    'donate.txid': 'ট্রানজ্যাকশন আইডি',
    'donate.txid.placeholder': 'এসএমএস থেকে TxID লিখুন',
    'donate.txid.label': 'ট্রানজ্যাকশন আইডি / রেফারেন্স',
    'donate.date': 'তারিখ',
    'donate.receipt': 'রশিদ',
    'donate.share': 'শেয়ার করুন',
    'donate.close': 'উইন্ডো বন্ধ করুন',
    'donate.how': 'কিভাবে টাকা দিবেন?',
    'donate.how.desc': 'অনুগ্রহ করে আপনার {method} অ্যাপ থেকে নিচের পার্সোনাল নাম্বারে "Send Money" করুন:',
    'donate.how.copy': 'কপি করুন',
    'donate.how.note': '* টাকা পাঠানোর পর নিচের ফর্মে আপনার ফোন নম্বর এবং ট্রানজ্যাকশন তথ্য প্রদান করুন।',
    'search.placeholder': 'ক্যাম্পেইন খুঁজুন...',
    'sort.urgent': 'সবচেয়ে জরুরি',
    'sort.funded': 'সবচেয়ে বেশি সংগৃহীত',
    'sort.latest': 'সর্বশেষ',
    'trust.badge': '১০০% নিরাপদ ও ভেরিফাইড প্ল্যাটফর্ম',
    'trust.title': 'আপনার আস্থাই আমাদের সবচেয়ে বড় সম্পদ',
    'trust.desc': 'আপনার কষ্টার্জিত অর্থ সঠিক হাতে পৌঁছানো নিশ্চিত করতে আমরা আমাদের ফিল্ড এজেন্টদের মাধ্যমে প্রতিটি ক্যাম্পেইন ম্যানুয়ালি যাচাই করি। কোনো গোপন ফি নেই, কোনো জটিল প্রক্রিয়া নেই।',
    'stat.raised': 'মোট সংগৃহীত',
    'stat.verified': 'ভেরিফাইড ক্যাম্পেইন',
    'stat.donors': 'সক্রিয় দাতা',
    'stat.success': 'সাফল্যের হার',
    'campaigns.subtitle': 'আপনার কাছে গুরুত্বপূর্ণ কারণগুলো খুঁজুন এবং সমর্থন করুন।',
    'campaigns.notfound': 'কোন ক্যাম্পেইন পাওয়া যায়নি',
    'campaigns.notfound.desc': 'আপনার অনুসন্ধান বা ফিল্টার পরিবর্তন করার চেষ্টা করুন।',
    'campaigns.all': 'সব',
    'details.notfound': 'ক্যাম্পেইন পাওয়া যায়নি',
    'details.back': 'ক্যাম্পেইনে ফিরে যান',
    'details.back.short': 'পিছনে',
    'details.verified': 'ভেরিফাইড',
    'details.share': 'এই ক্যাম্পেইনটি শেয়ার করুন',
    'details.guarantee.title': 'নিরাপদ দানের নিশ্চয়তা',
    'details.guarantee.desc': 'আপনার দান আমাদের নিরাপদ পেমেন্ট সিস্টেম দ্বারা সুরক্ষিত। আমরা তহবিল বিতরণে ১০০% স্বচ্ছতা নিশ্চিত করি।',
    'details.faq.title': 'সচরাচর জিজ্ঞাসিত প্রশ্নাবলী',
    'details.faq.q1': 'আমার টাকা কিভাবে ব্যবহার করা হবে?',
    'details.faq.a1': 'আপনার দানের ১০০% (পেমেন্ট গেটওয়ে ফি বাদে) সরাসরি ক্যাম্পেইন সুবিধাভোগীর কাছে যায়।',
    'details.faq.q2': 'আমার দান কি কর-ছাড়যোগ্য?',
    'details.faq.a2': 'হ্যাঁ, আমরা অফিসিয়াল রশিদ প্রদান করি যা বাংলাদেশে করের উদ্দেশ্যে ব্যবহার করা যেতে পারে।',
    'details.faq.q3': 'আমি কি গোপনে দান করতে পারি?',
    'details.faq.a3': 'অবশ্যই। আপনি পাবলিক দাতা তালিকা থেকে আপনার নাম এবং বার্তা লুকিয়ে রাখতে পারেন।',
    'details.raised.of': 'সংগৃহীত হয়েছে',
    'details.donors': 'দাতা',
    'details.left': 'দিন বাকি',
    'details.safe': 'নিরাপদ চেকআউটের নিশ্চয়তা',
    'details.organizer': 'আয়োজক',
    'details.organizer.name': 'আমার সাধন টিম',
    'details.report': 'এই ক্যাম্পেইনটি রিপোর্ট করুন',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('bn');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
